// import XLSX from "xlsx";

// // Function to read an excel sheet at given location, parse the third row of the sheet for the column names, and return an array of objects with the column names as keys and the values as the values.
// export const excelSheetToJSON = (path: string) => {
//   const workbook = XLSX.readFile(path);
//   const sheetName = workbook.SheetNames[0];
//   const sheet = workbook.Sheets[sheetName];
// };

export const gasTankless = [
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGL 199N1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTG-K-199N1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTG-K-199N2",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9900 SE 199",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9800 SEO 199",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9800 SE 199",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9900I SE 199",
    UEF: 0.95,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*160*P",
    UEF: 0.96,
  },
  {
    Brand: "VESTA",
    Model: "VRP-150",
    UEF: 0.95,
  },
  {
    Brand: "VESTA",
    Model: "VRS-199",
    UEF: 0.95,
  },
  {
    Brand: "VESTA",
    Model: "VRS-150",
    UEF: 0.95,
  },
  {
    Brand: "VESTA",
    Model: "VRP-199",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "CU199E (REU-N3237WC-US)",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU180I) REU-N2934FF-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "CU160I (REU-N2530FFC-US)",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU199E) REU-N3237W-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU180E) REU-N2934W-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "CU199I (REU-N3237FFC-US)",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU160E) REU-N2530W-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU199I) REU-N3237FF-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "CU160E (REU-N2530WC-US)",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "(RU160I) REU-N2530FF-US",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC199IP",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC199EP",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC160EP",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC160IP",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC199IN",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC199EN",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC160EN",
    UEF: 0.95,
  },
  {
    Brand: "RINNAI",
    Model: "RSC160IN",
    UEF: 0.95,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-240S2",
    UEF: 0.96,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-210S2",
    UEF: 0.96,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-180S2",
    UEF: 0.96,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-240A2",
    UEF: 0.95,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-180A2",
    UEF: 0.95,
  },
  {
    Brand: "NAVIEN",
    Model: "NPE-210A2",
    UEF: 0.95,
  },
  {
    Brand: "NORITZ",
    Model: "EZ111DV (GQ-C3259WX-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "EZ98DV (GQ-C2859WX-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "NCC199CDV (GQ-C3259WZ-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "EZ111DV (GQ-C3260WX-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "NCC199CDV (GQ-C3260WZ-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "NRCR92DV (GQ-C2660WXQ-FF US)",
    UEF: 0.95,
  },
  {
    Brand: "NORITZ",
    Model: "EZ98DV (GQ-C2860WX-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "NORITZ",
    Model: "NRCR111DV (GQ-C3260WXQ-FF US)",
    UEF: 0.96,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGR199N1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGS199N1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGR199X1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGS199X1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATI-340HX3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATI-340HX3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-340X3-NIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-340X3-PIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-340X3-NIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-340X3-PIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-340X3-NIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-340X3-PIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-340X3-GIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTI-340X3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTI-340X3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-240HX3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-240HX3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-240X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-240X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-240X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-240X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-240X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-240X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-240X3-GEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3J-OS-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3J-OS-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-240H 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-240H 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GT15-240-NO 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GT15-240-PO 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-240-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-240-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-240H-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-240H-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-240-GEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-240-LEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-240-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-240-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "JOHN WOOD",
    Model: "JWT-340H-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "JOHN WOOD",
    Model: "JWT-340H-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "GSWT-340H-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "GSWT-340H-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540HX3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540HX3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "TK-540X3-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "TK-540X3-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540X3-GEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540X3-LEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540HX3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540HX3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3-OS-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3S-DV-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-540P-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3S-DV-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TCT-199O-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GT15-340-NI 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GT15-340-PI 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATI-340H 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "T-H3-OS-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATI-340H 1*1",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TK-540P-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-340-NIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "TAKAGI",
    Model: "TCT-199O-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-340-PIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540H 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTI-340H-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540P-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTI-340H-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ACT-199O-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-340-GIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GT15-540-NO 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-340-LIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-340-NIH 1**",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540H 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-340-PIH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ATO-540P-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "A. O. SMITH",
    Model: "ACT-199O-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540P-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "SCT-199O-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "GTS-540P-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "STATE",
    Model: "SCT-199O-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540-GEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540P-GEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540-LEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-540P-LEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540P-NEH 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "MCT-199O-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "GT-540P-PEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "AMERICAN",
    Model: "MCT-199O-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540H-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540P-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LCT-199O-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540H-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-540P-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LCT-199O-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "TS-240X3-LEH 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-240X3-P 1*1",
    UEF: 0.95,
  },
  {
    Brand: "LOCHINVAR",
    Model: "LTO-240X3-N 1**",
    UEF: 0.95,
  },
  {
    Brand: "RHEEM",
    Model: "RTGH-S*11*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "RTGH-S*10*",
    UEF: 0.96,
  },
  {
    Brand: "RUUD",
    Model: "RUTGH-S*10*",
    UEF: 0.96,
  },
  {
    Brand: "RUUD",
    Model: "RUTGH-S*11*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "CRTGH-S*10*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "CRTGH-S*11*",
    UEF: 0.96,
  },
  {
    Brand: "RUUD",
    Model: "CRUTGH-S*11*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "ECERTGH-S*10*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "ECERTGH-S*11*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "RTGH-S*84*",
    UEF: 0.96,
  },
  {
    Brand: "RUUD",
    Model: "RUTGH-S*84*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "CRTGH-S*84*",
    UEF: 0.96,
  },
  {
    Brand: "RHEEM",
    Model: "ECERTGH-S*84*",
    UEF: 0.96,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*160*N",
    UEF: 0.96,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*180*N",
    UEF: 0.96,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*180*P",
    UEF: 0.96,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*200*N",
    UEF: 0.96,
  },
  {
    Brand: "ECOSENSE",
    Model: "CECOHS*200*P",
    UEF: 0.96,
  },
  {
    Brand: "BOSCH",
    Model: "T9800 SE 160",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9800 SEO 160",
    UEF: 0.95,
  },
  {
    Brand: "BOSCH",
    Model: "T9900 SE 160",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTG-K-160N2",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTG-K-160N1",
    UEF: 0.95,
  },
  {
    Brand: "BRADFORD WHITE",
    Model: "RTGL 160N1",
    UEF: 0.95,
  },
];

export const gasStorage = [
  {
    Brand: "RHEEM",
    Model: "XP40S12UHC50*",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "XP50T12UHC50*",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GPCT-40L 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GPCX-50L 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GC6-PS4050*V 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GPCC-40L 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "AMERICAN",
    Model: "PCG62-40S50L 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "6-40-*RPCS 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "STATE",
    Model: "GP6-40-*RPCSL 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GC6-PS5065*V 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GPCC-50L 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "AMERICAN",
    Model: "PCG62-50S65L 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "6-50-*XPCS 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "STATE",
    Model: "GP6-50-*XPCSL 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense",
    Model: "ENV-40N 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense Enercare",
    Model: "ENV-40N-ENER 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense Reliance Home Comfort",
    Model: "ENV-40N-RHC 1**",
    Volume: 38,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense",
    Model: "ENV-50N 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense Enercare",
    Model: "ENV-50N-ENER 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "Envirosense Reliance Home Comfort",
    Model: "ENV-50N-RHC 1**",
    Volume: 49,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G40-50* RH HE EC3",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-50* RH HE EC3",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G40-50* CN HE**",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "XG40S12UHN50*",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "ECE G40-50U CN HE*",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RUUD",
    Model: "PROU G40-50* RU HE EC3",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RICHMOND",
    Model: "12GUH40-50F*",
    Volume: 40,
    "Draw Pattern": "High",
    UEF: 0.9,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-50* CN HE**",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "RHEEM",
    Model: "XG50T12UHN50*",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "RHEEM",
    Model: "ECE G50-50U CN HE*",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "RUUD",
    Model: "PROU G50-50* RU HE EC3",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
  {
    Brand: "RICHMOND",
    Model: "12GUH50-50F*",
    Volume: 50,
    "Draw Pattern": "High",
    UEF: 0.88,
  },
];

export const gasResiCommercial = [
  {
    Brand: "RHEEM",
    Model: "XP50T12UHC76U0",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "GHE50S*-76**",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "XP50T12UHC100U0",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "GHE50S*-100**",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "HTP",
    Model: "PH100-119****",
    Volume: 112,
    UEF: 0.9,
  },
  {
    Brand: "HTP",
    Model: "PH100-80****",
    Volume: 75,
    UEF: 0.93,
  },
  {
    Brand: "HTP",
    Model: "PH100-55****",
    Volume: 53,
    UEF: 0.89,
  },
  {
    Brand: "HTP",
    Model: "PH76-80****",
    Volume: 77,
    UEF: 0.87,
  },
  {
    Brand: "HTP",
    Model: "PH76-60****",
    Volume: 58,
    UEF: 0.88,
  },
  {
    Brand: "HTP",
    Model: "PH76-50****",
    Volume: 48,
    UEF: 0.9,
  },
  {
    Brand: "AMERICAN",
    Model: "PG10 34 100 2*V 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "AMERICAN",
    Model: "VG6250T76NV 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "6G5076NVC 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "6-75- *TPDT 3**",
    Volume: 74,
    UEF: 0.86,
  },
  {
    Brand: "AMERICAN",
    Model: "VG6275T100*V 3**",
    Volume: 74,
    UEF: 0.86,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "6G75100*PDVH0* 3**",
    Volume: 74,
    UEF: 0.86,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GPHE-50 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "6-50-*TPDT 3**",
    Volume: 49,
    UEF: 0.88,
  },
  {
    Brand: "STATE",
    Model: "GP6-75- *TPDT 3**",
    Volume: 74,
    UEF: 0.86,
  },
  {
    Brand: "STATE",
    Model: "GP6-50-*TPDT 3**",
    Volume: 49,
    UEF: 0.88,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GDHE-75 3**",
    Volume: 74,
    UEF: 0.86,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GDHE-50 3**",
    Volume: 49,
    UEF: 0.88,
  },
  {
    Brand: "AMERICAN",
    Model: "VG6250T100*V 3**",
    Volume: 49,
    UEF: 0.88,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "6G5076NVC02 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "GSW WATER HEATERS",
    Model: "6G50100*PDVH 3**",
    Volume: 49,
    UEF: 0.88,
  },
  {
    Brand: "STATE",
    Model: "GHX-34-100 N 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "LOCHINVAR",
    Model: "SWL100035 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "STATE",
    Model: "GP6-50-YTVIT 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "LOCHINVAR",
    Model: "SWN100035 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "RELIANCE WATER HEATERS",
    Model: "6-50-YTVIT 1**",
    Volume: 48,
    UEF: 0.88,
  },
  {
    Brand: "A. O. SMITH",
    Model: "GSP-100 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "AMERICAN",
    Model: "PR-34-100 * 2**",
    Volume: 33,
    UEF: 0.9,
  },
  {
    Brand: "RUUD",
    Model: "PROU G50-76* RU HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "ECE G50-76U CN HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "XG50T12UHN76*0",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-76* CN HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-100* RH HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-76* RH HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "GHE50S*-100",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RICHMOND",
    Model: "12GUH50-100F*",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RUUD",
    Model: "PROU G50-100* RU HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "ECE G50-100U CN HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "XG50T12UHN100*0",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "PROP G50-100* CN HE EC3",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RHEEM",
    Model: "GHE50S*-76",
    Volume: 50,
    UEF: 0.89,
  },
  {
    Brand: "RICHMOND",
    Model: "12GUH50-76F*",
    Volume: 50,
    UEF: 0.89,
  },
];
